### ISSUE TITLE
How to not display world days in the server list?

### ISSUE THREAD

**Issue by qqqqww1** [StunlockStudios/vrising-dedicated-server-instructions#113]
I see that the number of days is not displayed in the details of some servers, but the servers I open display it. How can I cancel the display of this parameter?

![7a75b5df7c13383d5007a50c854686fa](https://user-images.githubusercontent.com/25215847/172523080-23e5fd83-7003-4048-89b0-7780857e071c.jpg)

**Comment by lucaspef** [comment]
You have to download a new version of gameserver from Steamcmd.

**Comment by qqqqww1** [comment]
> 

thanks!
