### ISSUE TITLE
the -persistentDataPath option does not work for settings

### ISSUE THREAD

**Issue by WXDawaken** [StunlockStudios/vrising-dedicated-server-instructions#12]
Hi !
I've tried to set up my server, and I use " -persistentDataPath" to set save path as you recommanded. But I found that it only works for the saving data, the server still try to use the default setting files , not the setting files in the "persistentDataPath".

**Comment by harderthanfire** [comment]
Make sure you are not setting GameSettingsPreset in ServerHostSettings.json, when I set that it then ignores whatever I set in ServerGameSettings.json

**Comment by harderthanfire** [comment]
Also you need to put those two json files inside a folder called Settings in the persistentDataPath

**Comment by WXDawaken** [comment]
> Also you need to put those two json files inside a folder called Settings in the persistentDataPath along with the admin and banlists.

Oh, I did not put the setting files in Setting folder, just put them in the persistentDataPath......Seems my mistake, thank you for the help
