### ISSUE TITLE
Any updates on Linux version?

### ISSUE THREAD

**Issue by Tannenfels** [StunlockStudios/vrising-dedicated-server-instructions#133]

**Comment by jpmarcotte** [comment]
This is literally issue #1. FYI, it's generally bad form to create duplicate issues that make it harder for the devs to manage their repo.

If you want an update about a known issue they are working on, their community areas (_e.g._ Discord) are the better places to ask, where their community managers can field and triage questions.

I recommend closing this issue and asking there.
