### ISSUE TITLE
VRisingServer.exe fails quietly on Windows Server Standard Core 2019

### ISSUE THREAD

**Issue by dijikul** [StunlockStudios/vrising-dedicated-server-instructions#134]
I have install Windows Server Core 2019 and am trying to configure the V-Rising Dedicated server using SteamCMD, which installs the V-Rising bits fine, but when I start the server using the provided batch file it fails silently without creating the log directory to see where things went wrong.

I realize this is a non-standard version of Windows (non-Gui Server core) but I'm trying to limit the resources.  Should this configuration be possible?

Thanks in advance.

**Comment by HSVAdam** [comment]
Does anyone know why this is?  I am having the same issue.

**Comment by dijikul** [comment]
@HSVAdam I was able to resolve this issue by installing the Server Core App Compatibility pack following the instructions here: https://learn.microsoft.com/en-us/windows-server/get-started/server-core-app-compatibility-feature-on-demand

**Comment by HSVAdam** [comment]
I maybe having a different issue, I have the app compatibility capability installed.  From even a fresh download of the server files and no configurations or game saves on the server when I run 'VRisingServer.exe' it loads everything up and seems normal then gets to the line "PersistenceV2 - Successfully serialized Persistence Header. Header was 778299 bytes large." and then it just stops.

**Comment by dijikul** [comment]
@HSVAdam looking at my logs for the line you specify I can see it streaming map chunks afterwards: 

![image](https://github.com/StunlockStudios/vrising-dedicated-server-instructions/assets/2670528/58236fd3-2b27-4bc5-aef4-7444b6356b4d)


This takes some time depending on how fast your storage is, and extra long the first time I think when it generates everything.

**Comment by HSVAdam** [comment]
Should not be any type of speed issue, the entire process just ends.
