### ISSUE TITLE
How can I add GameSettingsPreset as a parameter?

### ISSUE THREAD

**Issue by paulvilla** [StunlockStudios/vrising-dedicated-server-instructions#15]
I would like to be able to launch two servers with different game mode parameters, but I can't find the signature to do it.

I know that if I separate all the files it is possible, but I am mounting the multiserver installation with shared files and the most correct way is to put the differences by parameters in the second .bat, it would be ideal

**Comment by harderthanfire** [comment]
If you give each server it's own `-persistentDataPath` in the bat files you can then put a Settings folder in that path and each can have it's own ServerHostSettings.json allowing you to specify this.

**Comment by khct** [comment]
No command line parameter for the preset at this time, but what @harderthanfire says should work.

The `ServerHostSettings.json` in the `-persistentDataPath` `Settings` folder only need to contain the values that you want to override from the default file.
