### ISSUE TITLE
Server not showing up in "Find Servers" page

### ISSUE THREAD

**Issue by isadorasophia** [StunlockStudios/vrising-dedicated-server-instructions#19]
I am currently hosting a server in an Azure VM. My friends and I are able to successfully join the server when manually entering it as IP:Port with "Direct Connect".

However, I can't see it listed in the server lookup for "Find Servers". I tried tweaking the settings of the search, but that didn't help either, see:
![image](https://user-images.githubusercontent.com/7958854/169179231-0632881b-3946-4984-91a8-c6b377411d2d.png)

This is my json for setting up the server:
```json
{
	"Name": "<my-server>",
	"Description" : "<my-description>",
	"Port" : 27015,
	"QueryPort" : 27016,
	"MaxConnectedUsers" : 40,
	"MaxConnectedAdmins" : 4,
	"SaveName" : "<my-save>",
	"Password" : "<my-password>",
	"ListOnMasterServer" : true,
	"AutoSaveCount" : 40,
	"AutoSaveInterval" : 120,
	"GameSettingsPreset" : "StandardPvP"
}
```

Is there any specific parameter I might be missing to see it listed there?

Edit: Another detail which might help is that I am not logged in steam in the server machine.

Thank you!

**Comment by tcldark** [comment]
You are using the steam services query ports as your server's access ports.
Change them to default:
   "Port": 9876,
   "QueryPort": 9877
Then in the VM's network settings add both SteamQueryPort ports 27015-27016 UDP
And your server ports 9876-9877
Add them to inbound and outbound port rules.

PS: In the server search, set the latency to any. Since you still don't know your latency.

**Comment by isadorasophia** [comment]
Tweaking the port number fixed the issue! Thank you @tcldark 🙏 The latency is also a good catch.

**Comment by ImUrX** [comment]
I'm having the same issue but in a docker
```

**Comment by ImUrX** [comment]
Im having the same issue with docker, this is the config im using
```json
{
  "Name": "",
  "Description": "",
  "Port": 25569,
  "QueryPort": 25568,
  "MaxConnectedUsers": 50,
  "MaxConnectedAdmins": 5,
  "ServerFps": 30,
  "SaveName": "",
  "Password": "",
  "Secure": true,
  "ListOnMasterServer": true,
  "AutoSaveCount": 30,
  "AutoSaveInterval": 600,
  "GameSettingsPreset": "",
  "AdminOnlyDebugEvents": true,
  "DisableDebugEvents": false
}
```

I already checked and the 2 ports are being forwarded, and if I add the server to favorites all the info appears but I dont know what to do
