### ISSUE TITLE
Run server in linux

### ISSUE THREAD

**Issue by Cherrysaber** [StunlockStudios/vrising-dedicated-server-instructions#47]
Linux Support Please!!!

**Comment by ich777** [comment]
Duplicate of #1 

Currently possible through WINE.

I've created a Docker container see [here](https://github.com/ich777/docker-steamcmd-server/tree/vrising) on GitHub or [here](https://hub.docker.com/layers/steamcmd/ich777/steamcmd/vrising/images/sha256-c9dafa02191de81c1721b4e353172be79339fffab90b4261b34eb12fafdd69e2?context=explore) on DockerHub.

**Comment by nehart** [comment]
A Linux version of the Server would be highly appreciated

**Comment by ich777** [comment]
@nehart see #1 where the developers actually answered why there isn‘t a native Linux dedicated server yet.
