### ISSUE TITLE
cert is not authorized for appid 1829350 only 1604030 when trying to connect to dedicated server

### ISSUE THREAD

**Issue by bigluobo** [StunlockStudios/vrising-dedicated-server-instructions#6]
Hosted own server, cannot connect using direct connection

**Comment by derroobin** [comment]
did you start it with start_server_example.bat?
in that file there is an env variable set before running the server
`set SteamAppId=1604030`

maybe you have to run this command before starting the server

**Comment by bigluobo** [comment]
Solved! I wasn't using the bat file.
