### ISSUE TITLE
Not working and I am not sure why

### ISSUE THREAD

**Issue by Palatial** [StunlockStudios/vrising-dedicated-server-instructions#63]
Hey guys, I have never setup a private server before and I am not sure why it is not working. I have edited the servergame/serverhost setting json files a bit but thats about it.

This is the last string of command line I am getting, hopefully this helps.

![Capture](https://user-images.githubusercontent.com/106203158/170147760-35aa5d22-fcb2-44b9-85e6-c2de29513871.JPG)

**Comment by Shags3379** [comment]
Edit the example batch file to run the server, running it directly doesn't work for some reason.

**Comment by Palatial** [comment]
D:\SteamLibrary\steamapps\common\VRisingDedicatedServer>VRisingServer.exe -persistentDataPath ".\save-data" -serverName "Jabba's Palace" -saveName "Phase 1" -logFile ".\logs\VRisingServer.log"

This is what my bat file looks like. I have a feeling there is something wrong with this or if I need to rename the batch file or something.

I tried to run it and its just sitting on the command line
![Capture](https://user-images.githubusercontent.com/106203158/170179825-4b425f2b-c234-43e7-a32d-d8cd6822933f.JPG)

**Comment by Shags3379** [comment]
Yep, try the server now. It should be working.

**Comment by Palatial** [comment]
Oh apologies, I tried to run the bat file and this is all I am seeing. Pressing enter does nothing

**Comment by Shags3379** [comment]
The bat file output in your previous screenshot is all I see when my server is working successfully.

**Comment by Palatial** [comment]
Oh ok. I was looking for it on the global list and was unable to find anything so I assumed it wasn't working. 
Do you by chance know who to find the IP address of the server if you dont specify an address to bind to so I can try to connect to it manually?

**Comment by Palatial** [comment]
Awesome, thank you a ton for the info. Ill take a look at it after work :)

**Comment by Palatial** [comment]
Working! Thank you Shags
