### ISSUE TITLE
Unity.Jobs.LowLevel.Unsafe.PanicFunction_:Invoke()

### ISSUE THREAD

**Issue by tanadate-rungsripattanaporn** [StunlockStudios/vrising-dedicated-server-instructions#68]
![image](https://user-images.githubusercontent.com/66917530/170269463-e4d825a4-19c6-4d16-9fd4-a1c086a93b26.png)

im getting this in the end of log(Not closing process yet) so this message is error or not?

**Comment by SuperRayss** [comment]
What was the solution? Getting this on my end as well.
