### ISSUE TITLE
SteamCMD app ID

### ISSUE THREAD

**Issue by TheSlice21** [StunlockStudios/vrising-dedicated-server-instructions#7]
Terribly sorry to ask a silly question, I intend on hosting from another machine, is there an appid for the dedicated server using the anonymous credentials so I can download the server via steamcmd.

**Comment by khct** [comment]
The AppID for the server itself is `1829350`.

When running the server it should "identify" itself as the main parent app (`V Rising`), by using the AppID `1604030`. Which it should do by the fact that the `steam_appid.txt` is placed next to the executable.

**Comment by TheSlice21** [comment]
That worked, Thanks!
