### ISSUE TITLE
missing GameDataSettings.json

### ISSUE THREAD

**Issue by AsheriaX** [StunlockStudios/vrising-dedicated-server-instructions#73]
followed all the instructions correctly but the server crashes while attempting to load a config that didnt come with the server install via steam spent a good chunk of time googling and making an empty file just crashes it on attempted read any idea whats going seems like other people can run it just fine and arent encountering a similar issue 
edit: using the example batch seems to work but i would like to use my groups private save which isnt pvp yet any attempt to use our save causes it to look for this config and hit a null reference exception
edit 2: tried a clean install of the server and now even the unchanged install throws this im at a loss for what to do at this point
i have self hosted all kinds of dedicated servers in the past this is by far the most buggy impossible to troubleshoot one if anyone has any idea for a solution here i would appreciate the help

**Comment by fishd72** [comment]
Can you post a copy of the script or command line that you're using to start the server as well as the config you're trying to load?

**Comment by Sonaclov** [comment]
If I have a settings folder in the location of the persistentDatapath it will try to look for the file mentioned in the title.
I renamed the settings folder to see what would happen and the server boots (without the settings).

**Comment by AsheriaX** [comment]
sorry for the late response but i was able to fix it by just copying the folder on the pc where it worked wholesale im not really sure what specifically fixed it, but im thinking it might have had something to do with the game not being installed prior to the dedi since thats the only actual difference between the two pc's regarding v rising alone gonna close this issue ftm

**Comment by PiccoloYu** [comment]
I think I have encountered the same problem. How can I solve it
