### ISSUE TITLE
Will there be a Linux version?

### ISSUE THREAD

**Issue by ImDini** [StunlockStudios/vrising-dedicated-server-instructions#74]
I'd prefer to host my server on Ubuntu if possible instead of windows

**Comment by fishd72** [comment]
This is literally [#1](https://github.com/StunlockStudios/vrising-dedicated-server-instructions/issues/1)

**Comment by ImDini** [comment]
> This is literally [#1](https://github.com/StunlockStudios/vrising-dedicated-server-instructions/issues/1)
Thank you. My mistake for not seeing it with the previous 70 other issues. SMILE
