### ISSUE TITLE
Is there a way to get current server status and data externally? (for a discord bot, etc)

### ISSUE THREAD

**Issue by AssisrMatheus** [StunlockStudios/vrising-dedicated-server-instructions#87]
Is there somewhere, like a local port on the server, or a self-updating text file, that we can read off of if we have access to the server. To read current online players, total amount of players. Who killed who, etc?

We wish to make some integrations on our discord server(that runs off of the same server machine of the dedicated server) and would be nice to have access to those features

**Comment by Xartrick** [comment]
You can query servers by using Steam's server queries.

https://developer.valvesoftware.com/wiki/Server_queries

**Comment by AssisrMatheus** [comment]
> You can query servers by using Steam's server queries.
> 
> https://developer.valvesoftware.com/wiki/Server_queries

Ohh awesome, we'll give that a try. Thank You!

**Comment by AssisrMatheus** [comment]
> You can query servers by using Steam's server queries.
> 
> https://developer.valvesoftware.com/wiki/Server_queries

Do you know if that works with self-hosted servers. We have a dedicated server hosted in oracle, but it's not an "official" server

**Comment by Xartrick** [comment]
Yes, it does. Local, self-hosted and managed servers are all running dedicated servers behind.

Beware that the port you will query is not the server's port you use to connect.

You can use Steam's API to get this port : `https://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=1.2.3.4`

If my server IP is `1.2.3.4` and my port is `1337`, I have to query `1.2.3.4:1338` (`addr` field).

```json
{
    "response": {
        "success": true,
        "servers": [
            [...]
            {
                "addr": "1.2.3.4:1338",
                "gmsindex": -1,
                "steamid": "90159444323854343",
                "appid": 1604030,
                "gamedir": "V Rising",
                "region": -1,
                "secure": true,
                "lan": false,
                "gameport": 1337,
                "specport": 0
            },
            [...]
        ]
    }
}```
