### ISSUE TITLE
Cannot connect to localhost(127.0.0.1) by LAN or WAN

### ISSUE THREAD

**Issue by ithelpm** [StunlockStudios/vrising-dedicated-server-instructions#88]
SteamLog [SDR k_ESteamNetworkingSocketsDebugOutputType_Msg] [Data] Ignored bad "IP:PORT".  Stray data packet from host with no connection.  Ignoring.

UnityEngine.Logger:Log(LogType, Object)

UnityEngine.Debug:Log(Object)

Stunlock.Network.Steam.Wrapper.SteamSocketNetworkingLogs:OnLog(LogSource, ESteam

NetworkingSocketsDebugOutputType, IntPtr)

**========EDIT========**

this is the LOG when new connection from other IP:
SteamLog [SDR k_ESteamNetworkingSocketsDebugOutputType_Warning] SteamNetworkingSockets lock held for 8.6ms.  (Performance warning.)  ServiceThread,ThinkPingProb

es,EnsureDataCenterRoutesValid

This is usually a symptom of a general performance problem such as thread starvation.

UnityEngine.Logger:Log(LogType, Object)

UnityEngine.Debug:LogWarning(Object)

Stunlock.Network.Steam.Wrapper.SteamSocketNetworkingLogs:OnLog(LogSource, ESteam

NetworkingSocketsDebugOutputType, IntPtr)

**Comment by teekennedy** [comment]
This is not an issue with this server. Rather this is how localhost is supposed to work. If you set the server to listen on `127.0.0.1`, or any other IPv4 address that starts with `127`, the operating system will only allow connections _if they're coming from the same machine_, i.e. the local host.

If you change the IP address of the server to match your LAN IP address, others will be able to connect to it from the LAN, but not WAN.

If you want the server to accept connections no matter where they're coming from, you should use the special IP address `0.0.0.0`.

**Comment by ithelpm** [comment]
Well, I do connect from a "local" machine. I think it might be somewhere wrong in my setting or something else.
Then it appeared on the server this didn't know somehow...
I'll close this issue and thanks for @teekennedy 's help
