### ISSUE TITLE
Host and play on the same machine

### ISSUE THREAD

**Issue by aweftr** [StunlockStudios/vrising-dedicated-server-instructions#95]
I host a dedicated server on my own machine with a public IP, and I want to play as a client on this machine when I am free. 
However, when I connect to the server with command `Connect IP Port`, the connection is timed out and no log file is shown. 
When I use `ConnectLan IP Port`, the log file is shown as follows:
```
SteamLog [SDR k_ESteamNetworkingSocketsDebugOutputType_Msg] [Data] Ignored bad [IP:Port].  Stray data packet from host with no connection.  Ignoring.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Stunlock.Network.Steam.Wrapper.SteamSocketNetworkingLogs:OnLog(LogSource, ESteamNetworkingSocketsDebugOutputType, IntPtr)
```
Can I host and play on the same machine or do I have to host on one machine and play on another PC? 
If I can, how can I connect to my server?

The host setting: 
```
{
  "Name": "Aweftr's Server",
  "Description": "Have fun",
  "Address": "IP",
  "Port": Port,
  "QueryPort": Port-2,
  "MaxConnectedUsers": 40,
  "MaxConnectedAdmins": 2,
  "ServerFps": 30,
  "SaveName": "world1",
  "Password": "",
  "Secure": true,
  "ListOnMasterServer": false,
  "AutoSaveCount": 50,
  "AutoSaveInterval": 600,
  "GameSettingsPreset": "",
  "AdminOnlyDebugEvents": true,
  "DisableDebugEvents": false
}
```

**Comment by rwmatthews** [comment]
You can host and play on the same machine. What happens if you try to connect to 127.0.0.1 (try with and without port) instead of your public or network IP?

**Comment by aweftr** [comment]
I can connect after today's update using the same command. Thanks.
